excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://harrysuke.github.io
title: Kairi Juri
tagline: A log of everyday life
description: My Github.io 
theme: just-the-docs
paginate: 5
